version: '2'
services:
  velox:
    container_name: velociraptor
    #image: wlambert/velociraptor
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./velociraptor:/velociraptor/:rw
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8889:8889"
    restart: unless-stopped
